version: '2'

services:
    mkmprovider:
        build: MKMProvider
        volumes:
            - "./MKMProvider:/myapp"
        ports:
            - 3002:3002
        command: php -S 0.0.0.0:3002

    mkmprice:
        build: MKMPrice
        volumes:
            - "./MKMPrice:/myapp"
        ports:
            - 3001:3001
        command: nodejs index.js
    mkmbot:
        build: MKMBot
 #       volumes:
  #          - "./MKMBot/src:/myapp"
        command: php mtg-bot.php
