version: '2'

services:
    mkmprovider:
        build: MKMProvider
        volumes:
            - "./MKMProvider:/myapp"
        ports:
            - 3002:3002
        command: php -S 0.0.0.0:3002
        environment:
            MKM_APP_TOKEN: ${MKM_APP_TOKEN}
            MKM_APP_SECRET: ${MKM_APP_SECRET}
            MKM_ACCESS_TOKEN: ${MKM_ACCESS_TOKEN}
            MKM_ACCESS_SECRET: ${MKM_ACCESS_SECRET}

    mkmprice:
        build: MKMPrice
        volumes:
            - "./MKMPrice:/myapp"
        links:
            - mkmprovider:mkmprovider
        ports:
            - 3001:3001
        command: nodejs index.js

    mkmbot:
        build: MKMBot
        links:
            - mkmprice:mkmprice
        volumes:
            - "./MKMBot/src:/myapp"
        command: php mtg-bot.php
        environment:
            TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
