FROM ubuntu

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    zlib1g-dev \
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get install -y nodejs

#RUN cd /myapp && npm install

WORKDIR /myapp

EXPOSE 3001
